Vanilla PHP version of Xendit Demo
xendit/checkout-demo-php pull request #1
Opened 2021-10-05 16:53 UTC by ndosibarani

2021-10-07 03:28 UTC, xen-HendryZheng commented on README.md
> +Composer is required. Get composer from https://getcomposer.org/download/
Please also state, what is the minimum PHP version.

2021-10-07 03:44 UTC, xen-HendryZheng commented on src/app/Router.php
> +                return 'not_found_oooi';
Please change to proper message.
Request Not Found

2021-10-07 04:24 UTC, xen-HendryZheng commented on src/public/index.php
> +    header('Conten-Type: application/json');
header('Content-Type')

2021-10-07 04:25 UTC, xen-HendryZheng commented on src/services/checkout/CheckoutService.php
> +        header('Conten-Type: application/json');
Content-Type

2021-10-07 04:47 UTC, xen-HendryZheng commented on src/views/checkout/checkout.php
> +                                    href="https://github.com/xendit/checkout-demo"
Change to this: https://github.com/xendit/checkout-demo-php

2021-10-07 04:48 UTC, xen-HendryZheng commented on src/views/checkout/checkout.php
> +                                Xendit is the leading payment gateway for
Xendit is the leading payment gateway for
                                Indonesia, Philipines and Southeast Asia.

2021-10-07 05:18 UTC, xen-HendryZheng commented on src/services/checkout/CheckoutService.php
> +        $createdInvoice = \Xendit\Invoice::create($params);
Please handle Try and Catch here. If the API call is failing, should return error message to front end.

Attached:
![image](https://user-images.githubusercontent.com/90175540/136322478-663be568-734b-40b9-8052-5c09e07098b7.png)

Something like this:
```
$resp = [];
try{
    $createdInvoice = \Xendit\Invoice::create($params);
    $resp =  $createdInvoice;
}catch(ApiException $e){
    $resp['message'] = $e->getMessage();
}

return json_encode($resp);
```
Just a reference, you may or may not follow. You can do it with your style.

2021-10-07 05:32 UTC, xen-HendryZheng requested changes
Please check each single comment I've attached on the respective files.

2021-10-08 12:15 UTC, ndosibarani commented
all feedback updated, please kindly review.

2021-10-08 16:21 UTC, xen-HendryZheng requested changes
Last final comment.

2021-10-08 16:21 UTC, xen-HendryZheng commented on src/services/checkout/CheckoutService.php
> +            http_response_code(501);
@ndosibarani Can you return the http status code from Xendit exception?

```
catch(ApiException $e){
      http_response_code($e->getCode());
      $resp['message'] = $e->getMessage();
  }
```

2021-10-11 08:29 UTC, xen-HendryZheng approved these changes
it's good.

2021-10-11 13:19 UTC, merged